### ISSUE TITLE
Errors in local deployment with docker-compose-local

### ISSUE THREAD

**Issue by drmckay-kirill** [metlo-labs/metlo#69]
Hello! I tried to start Metlo in local environment with `docker-compose-local.yaml` file:
`sudo docker-compose -f docker-compose-local.yaml up` in repo root directory.

Firstly, I get the next error: `Service 'ingestor' failed to buid: ADD failed: forbidden path outside the build context: ../../../backend ()`.
So, I changed `ADD ../../../backend backend` to `ADD ./backend backend`, and `ADD ../../../common common` to `ADD ./common common` in all dockerfiles in `deploy directory`.
And it works.

But the next error has been appeared, like in previous issue (https://github.com/metlo-labs/metlo/issues/32):
![image](https://user-images.githubusercontent.com/17834111/199165282-7512f9be-b96e-4735-9a17-d28fdfa5bd12.png)

Could you please help me? Thanks!

**Comment by AHarmlessPyro** [comment]
Hi @drmckay-kirill , it seems like you're trying to build docker images from scratch. We would recommend using the uploaded docker images since we try to maintain them in a working state. 

If you do wish to build the images by yourself, you can use the [Makefile](https://github.com/metlo-labs/metlo/blob/develop/Makefile) located in the project root. Then you can use the provided [docker-compose](https://github.com/metlo-labs/metlo/blob/develop/docker-compose.yaml) file after supplying the given env vars to start Metlo locally or use the [metlo-deployment.py](https://github.com/metlo-labs/metlo/blob/develop/manage-deployment.py) script to autofill the env vars and start the docker compose. 

Let us know if that fixes the build issues for you 😃

**Comment by drmckay-kirill** [comment]
Thanks! It's my missunderstanding. I should use `docker-compose` file instead, it works now.
